export const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST'
export const GET_PRODUCT_INFO = 'GET_PRODUCT_INFO'
export const GET_CATEGORY_LIST = 'GET_CATEGORY_LIST'
export const GET_BRAND_LIST = 'GET_BRAND_LIST'
